image: golang:1.20

stages:
  - build

build_master:
  stage: build
  script:
    - mkdir -p $GOPATH/src/$CI_PROJECT_NAME
    - cp -R $CI_PROJECT_DIR/. $GOPATH/src/$CI_PROJECT_NAME/
    - cd $GOPATH/src/$CI_PROJECT_NAME
    - go build -o $CI_PROJECT_NAME main.go
    - printf "\nenv:" >> .config.yml
    - printf " prod" >> .config.yml
    - curl "${CONFIG_SERVER}" -fd "`cat .config.yml`" > conf/dev/app.conf
    - mv $GOPATH/src/$CI_PROJECT_NAME/$CI_PROJECT_NAME $CI_PROJECT_DIR/$CI_PROJECT_NAME
    - mv $GOPATH/src/$CI_PROJECT_NAME/conf/dev/app.conf $CI_PROJECT_DIR/conf/dev/app.conf
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_NAME
      - conf
  only:
    - local